---
#- name: Instalações Basicas
#  hosts: todos

#  user: root
#  become: yes

#  roles:
#    - basicos

- name: Configurando Manager
  hosts: manager

  user: root
  become: yes

  roles:
    - manager