---
# tasks file for upgrade

- name: CheckNginx
  shell: systemctl is-active nginx
  register: nginx_status
  ignore_errors: yes

- name: PararNginx
  service:
    name: nginx
    state: stopped
  when: nginx_status.stdout == "active"
  notify: verify_nginx_stopped